version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    container_name: medusa-meilisearch
    environment:
      MEILI_MASTER_KEY: yoursecretmasterkey
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  meilisearch_data:
